server {
    listen 80;
    
    location /health {
        return 200 "Gateway OK\n";
        add_header Content-Type text/plain;
    }
    
    location /api/auth/ {
        proxy_pass http://auth-service:3000/api/auth/;
        proxy_set_header Host $host;
    }
    
    location /api/patients/ {
        proxy_pass http://patient-service:3001/api/patients/;
        proxy_set_header Host $host;
    }
    
    location /api/doctors/ {
        proxy_pass http://doctor-service:3002/api/doctors/;
        proxy_set_header Host $host;
    }
    
    location /api/appointments/ {
        proxy_pass http://appointment-service:3003/api/appointments/;
        proxy_set_header Host $host;
    }

    location = /api/appointments {
        proxy_pass http://appointment-service:3003/api/appointments;
        proxy_set_header Host $host;
    }
    
    location /api/telemedicine/ {
        proxy_pass http://telemedicine-service:3004/api/telemedicine/;
        proxy_set_header Host $host;
    }
    
    location /api/payments/ {
        proxy_pass http://payment-service:3005/api/payments/;
        proxy_set_header Host $host;
    }
    
    location /api/notifications/ {
        proxy_pass http://notification-service:3006/api/notifications/;
        proxy_set_header Host $host;
    }
}
