events {}

http {
  upstream auth_service        { server auth-service:3000; }
  upstream patient_service     { server patient-service:3001; }
  upstream doctor_service      { server doctor-service:3002; }
  upstream appointment_service { server appointment-service:3003; }
  upstream telemedicine_service { server telemedicine-service:3004; }
  upstream payment_service     { server payment-service:3005; }
  upstream notification_service { server notification-service:3006; }

  server {
    listen 80;

    location /api/auth/          { proxy_pass http://auth_service/; }
    location /api/patients/      { proxy_pass http://patient_service/; }
    location /api/doctors/       { proxy_pass http://doctor_service/; }
    location /api/appointments/  { proxy_pass http://appointment_service/; }
    location /api/telemedicine/  { proxy_pass http://telemedicine_service/; }
    location /api/payments/      { proxy_pass http://payment_service/; }
    location /api/notifications/ { proxy_pass http://notification_service/; }
  }
}
